# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: arc-runner-set

    container:
      image: docker:28.4-cli
      # image: ghcr.io/actions/actions-runner:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: List PWD
        run: |
          echo "PWD is $(pwd)"
          ls -lR .

      # - name: What Docker do I have?
      #   run: docker version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1
        with:
          # name: arc-demo
          # driver: kubernetes
          # driver-opts: namespace=arc-runners
          name: buildkitd
          driver: kubernetes
          driver-opts: namespace=arc-runners

      - name: List Builders
        run: docker buildx ls
      
      - name: Build Docker Image
        uses: docker/build-push-action@v6.18.0
        with:
          # builder: arc-demo
          # tags: arc-demo
          builder: buildkitd
          tags: pre-created